create table public.visitas (id bigint generated by default as identity primary key,nombre text not null,apellido text not null,mensaje text,created_at timestamptz not null default now());
alter table public.visitas enable row level security;
create policy "visitantes pueden registrar" on public.visitas for insert to anon with check (char_length(nombre) between 1 and 80 and char_length(apellido) between 1 and 80 and (mensaje is null or char_length(mensaje)<=500));
create policy "solo administradores autenticados pueden leer" on public.visitas for select to authenticated using (true);
